markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "footnotes"]
highlighter: pygments
paginate: 5
baseurl: /
permalink: /:title
paginate_path: "/page/:num/"
author_dir: author
category_dir: tag

exclude: [README.md, LICENSE, vendor, Gemfile]

gems:
  - jekyll-sitemap
  - jekyll-minifier


# ########################### #
# Configure beneath this line #
# ########################### #

name: Your Jekyll Site
description: Blogging about things
meta_description: Blogging about things on your new Jekyll site
url: localhost:4000
scheme: http #mainly used for xml feeds


logo: false
cover: false
disqus: false
author: author-slug
language: English

# ########################### #
